DROP TABLE IF EXISTS trips;
CREATE TABLE trips (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    date TEXT NOT NULL,
    lr_number TEXT,
    vehicle_id INTEGER REFERENCES vehicles(id),
    type TEXT,
    party_id INTEGER REFERENCES parties(id),
    from_loc TEXT,
    to_loc TEXT,
    quantity REAL,
    rate REAL,
    driver_name TEXT,
    material TEXT,
    rate_type TEXT,
    billed_amount REAL,
    driver_payment REAL DEFAULT 0,
    detention_charges REAL DEFAULT 0,
    gps_cost REAL DEFAULT 0,
    loading_charge REAL DEFAULT 0,
    unloading_charge REAL DEFAULT 0,
    police_charges REAL DEFAULT 0,
    sim_tracking REAL DEFAULT 0,
    union_charges REAL DEFAULT 0,
    weight_charges REAL DEFAULT 0,
    other_charges REAL DEFAULT 0,
    brokerage REAL DEFAULT 0,
    builty_commission REAL DEFAULT 0,
    late_fees REAL DEFAULT 0,
    material_damage REAL DEFAULT 0,
    shortage_amount REAL DEFAULT 0,
    shortage_qty REAL DEFAULT 0,
    tds REAL DEFAULT 0,
    other_deductions REAL DEFAULT 0,
    fuel_amount REAL DEFAULT 0,
    fuel_vendor_id INTEGER REFERENCES vendors(id),
    driver_adv_amount REAL DEFAULT 0,
    driver_adv_vendor_id INTEGER REFERENCES vendors(id),
    party_advance REAL DEFAULT 0,
    payment_received REAL DEFAULT 0,
    owner_name TEXT,
    fixed_rate_amount REAL DEFAULT 0,
    owner_rate REAL DEFAULT 0,
    owner_amount REAL DEFAULT 0,
    paid_to_owner REAL DEFAULT 0,
    pending_to_owner REAL DEFAULT 0,
    agent_commission REAL DEFAULT 0,
    builty_expense REAL DEFAULT 0,
    conductor_expense REAL DEFAULT 0,
    fine REAL DEFAULT 0,
    labour_charges REAL DEFAULT 0,
    parking REAL DEFAULT 0,
    puncture REAL DEFAULT 0,
    toll REAL DEFAULT 0,
    urea REAL DEFAULT 0,
    loading_expense REAL DEFAULT 0,
    unloading_expense REAL DEFAULT 0,
    wear_tear REAL DEFAULT 0,
    weighbridge_charges REAL DEFAULT 0,
    other_expense REAL DEFAULT 0,
    misc_vendor_id INTEGER REFERENCES vendors(id),
    lr_received TEXT
);
